# Nome da aplicacao
spring.application.name=UniSolidaria

# Conexao com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/unisolidaria
spring.datasource.username=postgres
spring.datasource.password=unisolidaria123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuracao para mostrar o SQL no console
spring.jpa.properties.hibernate.format_sql=true